# Generated by Django 4.0.5 on 2022-07-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='qu  estion',
        ),
    ]
