# Generated by Django 4.0.5 on 2022-07-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
