# Generated by Django 4.0.5 on 2022-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_qname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qname',
            field=models.CharField(max_length=16),
        ),
    ]
