# Generated by Django 4.0.5 on 2022-07-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_question_qname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
