# Generated by Django 4.0.5 on 2022-07-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_remove_member_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
    ]
