# Generated by Django 3.2.13 on 2022-07-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_alter_centerinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agid', models.AutoField(primary_key=True, serialize=False)),
                ('agentno', models.CharField(max_length=6)),
                ('sido', models.CharField(max_length=2)),
                ('gugun', models.CharField(max_length=4)),
                ('ro', models.CharField(max_length=10)),
                ('agentname', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('atno', models.CharField(max_length=12)),
                ('atname', models.CharField(max_length=10)),
                ('attel', models.CharField(max_length=10)),
                ('atfdate', models.CharField(max_length=10)),
                ('atedate', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-atid'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('appno', models.CharField(max_length=11)),
                ('pdate', models.CharField(max_length=10)),
                ('fdate', models.CharField(max_length=10)),
                ('edate', models.CharField(max_length=10)),
                ('ptime', models.CharField(max_length=5)),
                ('insptype', models.CharField(default='', max_length=4)),
                ('msg', models.TextField(null=True)),
                ('fnames', models.CharField(max_length=255, null=True)),
                ('agid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='check.agent')),
            ],
            options={
                'db_table': 'apply',
                'ordering': ['-appid'],
            },
        ),
        migrations.CreateModel(
            name='Carzipcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sido', models.CharField(max_length=20)),
                ('gugun', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'carzipcode',
            },
        ),
        migrations.CreateModel(
            name='InspFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insptype', models.CharField(max_length=4)),
                ('carsize', models.CharField(max_length=2)),
                ('carname', models.CharField(max_length=10)),
                ('fee', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'inspfee',
            },
        ),
        migrations.AlterModelOptions(
            name='centerinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='centerinfo',
            table='centerinfo',
        ),
        migrations.CreateModel(
            name='ApplyUser',
            fields=[
                ('ausrid', models.AutoField(primary_key=True, serialize=False)),
                ('carno', models.CharField(max_length=9)),
                ('appname', models.CharField(max_length=10)),
                ('carname', models.CharField(max_length=10)),
                ('apptel', models.CharField(max_length=10)),
                ('alttel', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=10)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('appid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='check.apply')),
            ],
            options={
                'db_table': 'applyuser',
            },
        ),
    ]
